# Generated by Django 4.1.3 on 2022-12-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_in_japanese', models.CharField(help_text='Enter a word in japanese', max_length=50, verbose_name='Japanese word')),
                ('translate_word', models.CharField(help_text='Enter the word translation', max_length=50, verbose_name='Word translated')),
                ('sentence_in_japanese', models.CharField(blank=True, help_text='Enter a sentence in japanese', max_length=150, verbose_name='Japanese sentence')),
                ('sentence', models.CharField(blank=True, help_text='Enter translation', max_length=250, verbose_name='Japanese the sentence translation')),
                ('part_of_speech', models.CharField(choices=[('A', 'Adjective'), ('I', 'Interjection'), ('N', 'Noun'), ('P', 'Phrase'), ('Q', 'Quantifier'), ('V', 'Verb'), ('N', 'Noun'), ('IDK', 'IDK')], default='IDK', max_length=3)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['part_of_speech'],
            },
        ),
    ]
