# Generated by Django 4.1.3 on 2022-12-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='words',
            options={'ordering': ['part_of_speech'], 'verbose_name': 'words', 'verbose_name_plural': 'words'},
        ),
    ]
