# Generated by Django 4.1.3 on 2022-12-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_words_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='sentence',
            field=models.CharField(blank=True, help_text='Enter the sentence translation', max_length=250, verbose_name='Sentence translation'),
        ),
        migrations.AlterField(
            model_name='words',
            name='sentence_in_japanese',
            field=models.CharField(blank=True, help_text='Enter a sentence in Japanese with the word in Japanese', max_length=150, verbose_name='Japanese sentence'),
        ),
        migrations.AlterField(
            model_name='words',
            name='word_in_japanese',
            field=models.CharField(help_text='Enter a word in Japanese', max_length=50, verbose_name='Japanese word'),
        ),
    ]
