# Generated by Django 4.1.3 on 2022-12-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_words_sentence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='has_kanji',
            field=models.BooleanField(default=False, help_text='Check if there is a kanji character in the word in Japanese', verbose_name='Kanji character in the word in Japanese'),
        ),
        migrations.AlterField(
            model_name='words',
            name='part_of_speech',
            field=models.CharField(choices=[('A', 'Adjective'), ('I', 'Interjection'), ('N', 'Noun'), ('P', 'Phrase'), ('Q', 'Quantifier'), ('V', 'Verb'), ('N', 'Noun'), ('O', 'Other')], default='O', max_length=3),
        ),
    ]
